# Generated by Django 6.0.5 on 2026-05-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
