# Generated by Django 6.0.5 on 2026-06-04 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_associated_lead'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='associated_lead',
            field=models.ForeignKey(blank=True, db_column='associated_lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead'),
        ),
    ]
