# Generated by Django 6.0.5 on 2026-06-14 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_associated_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='deal_owner',
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_owner',
            field=models.ManyToManyField(blank=True, related_name='owned_deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
